dist: focal
language: cpp
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T sfinae-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uxmiler:$BINTRAY_API_KEY "https://api.bintray.com/content/xmiler/otus_cpp/hw3_sfinae/$TRAVIS_BUILD_NUMBER/sfinae-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  on: hw3_sfinae
